######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 26 10:27:52 2012
######################################################################

CONFIG += shared console qt warn_on release
TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += ../common/ComFunctions.h
SOURCES += src/main.cpp ../common/ComFunctions.cpp
